# This file was generated by GoReleaser. DO NOT EDIT.
class Fpick < Formula
  desc "pick files you want"
  homepage ""
  url "https://github.com/sawadashota/fpick/releases/download/v0.2.0/fpick_0.2.0_macOS_64-bit.tar.gz"
  version "0.2.0"
  sha256 "600793dcd730b904249fcb3d00d5608fcc28b31a7541d19ec4d21ccd6b57069e"

  def install
    bin.install "fpick"
  end

  test do
    system "#{bin}/fpick -h"
  end
end
