# This file was generated by GoReleaser. DO NOT EDIT.
class Fpick < Formula
  desc "pick files you want"
  homepage ""
  url "https://github.com/sawadashota/fpick/releases/download/v0.0.5/fpick_0.0.5_macOS_64-bit.tar.gz"
  version "0.0.5"
  sha256 "e922c822b2ba0faa48a18ca4d3c0a7180f993db5e3f44c65fcf7df6b06204656"

  def install
    bin.install "fpick"
  end

  test do
    system "#{bin}/fpick -h"
  end
end
