# This file was generated by GoReleaser. DO NOT EDIT.
class Gorew < Formula
  desc "Golang cli management tool"
  homepage ""
  version "2.0.0-beta1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sawadashota/gorew/releases/download/v2.0.0-beta1/gorew_2.0.0-beta1_macOS_64-bit.tar.gz"
    sha256 "f1e238c7672655341edb352530a0dec94d280788f659f0b4fbfbf956d862a058"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sawadashota/gorew/releases/download/v2.0.0-beta1/gorew_2.0.0-beta1_linux_64-bit.tar.gz"
      sha256 "b9913d62a914b675fdd2f4e6c59adc9e75908ad7cf24ba5f4ad8338f53e2758d"
    end
  end

  def install
    bin.install "gorew"
  end

  test do
    system "#{bin}/gorew -h"
  end
end
