# This file was generated by GoReleaser. DO NOT EDIT.
class OrbUpdate < Formula
  desc "Update Orbs versions"
  homepage "https://github.com/sawadashota/orb-update"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sawadashota/orb-update/releases/download/0.2.2/orb-update_0.2.2_macOS_64-bit.tar.gz"
    sha256 "0041b813ab688ae489dcf654a271df4f5a26a99b9c28e3c782c64045eea5617c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sawadashota/orb-update/releases/download/0.2.2/orb-update_0.2.2_linux_64-bit.tar.gz"
      sha256 "23fdfe4ec9d4e0334f46cd13a457f13a3eb0a4d2ab6d5ea250dc2ca0c7e9286f"
    end
  end

  def install
    bin.install "orb-update"
  end

  test do
    system "#{bin}/orb-update -h"
  end
end
