# This file was generated by GoReleaser. DO NOT EDIT.
class OrbUpdate < Formula
  desc "Update Orbs versions"
  homepage "https://github.com/sawadashota/orb-update"
  version "0.3.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sawadashota/orb-update/releases/download/0.3.2/orb-update_0.3.2_macOS_64-bit.tar.gz"
    sha256 "6f064936389069e8b94760c67a4f4d4187871744fd6ab304a036ff15f49410d0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sawadashota/orb-update/releases/download/0.3.2/orb-update_0.3.2_linux_64-bit.tar.gz"
      sha256 "a3e2fc7440c6d37fa974801d0e3e971435adf96a1e6f680257abf4ff5d0bb3fa"
    end
  end

  def install
    bin.install "orb-update"
  end

  test do
    system "#{bin}/orb-update -h"
  end
end
