# This file was generated by GoReleaser. DO NOT EDIT.
class OrbUpdate < Formula
  desc "Update Orbs versions"
  homepage ""
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sawadashota/orb-update/releases/download/0.1.2/orb-update_0.1.2_macOS_64-bit.tar.gz"
    sha256 "8b4a5761c422385aa3a0b0862f63186e623707e678b51d87d2e4c45ceeb4ffd3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sawadashota/orb-update/releases/download/0.1.2/orb-update_0.1.2_linux_64-bit.tar.gz"
      sha256 "5ef740e48de90496e071300ed00817629c86bf9cf74732f40b4b143724dcf3fc"
    end
  end

  def install
    bin.install "orb-update"
  end

  test do
    system "#{bin}/orb-update -h"
  end
end
